import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

// First font
const erbar = localFont({
  src: [
    { path: "../public/fonts/fonnts.com-ERBAR-W01-LIGHT.ttf", weight: "400" },
    { path: "../public/fonts/fonnts.com-ERBAR-W01-LIGHT.ttf", weight: "700" },
  ],
  variable: "--font-erbar",
});

// Second font
const museo = localFont({
  src: [
    { path: "../public/fonts/Museo700-Regular.otf", weight: "400" },
    { path: "../public/fonts/Museo700-Regular.otf", weight: "600" },
  ],
  variable: "--font-museo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${erbar.variable} ${museo.variable} antialiased`}
        
      >
        {children}
      </body>
    </html>
  );
}
